### ISSUE TITLE
在iPad OS 14.5 下, 对战和打工详情是空白的, 在iPhone下正常

### ISSUE THREAD

**Issue by nagaame** [JoneWang/imink#10]
已经正常登录

截图如下

打工详情
![IMG_0003](https://user-images.githubusercontent.com/6214936/116398665-a1ccab00-a85a-11eb-8717-703ec866456d.PNG)

对战详情
![IMG_0004](https://user-images.githubusercontent.com/6214936/116398680-a729f580-a85a-11eb-95fb-9af74bbb7df4.PNG)

**Comment by JoneWang** [comment]
感谢反馈！
请问在 iPad 上 iOS 14.5 之前的系统版本是否正常？因为有特别提到 iOS 14.5。
重启 imink 后是否能解决？

**Comment by nagaame** [comment]
> 感谢反馈！
> 请问在 iPad 上 iOS 14.5 之前的系统版本是否正常？因为有特别提到 iOS 14.5。
> 重启 imink 后是否能解决？

之前的版本不知道, 我是升级了新的OS版本才安装您的APP的, 重启没有解决, 只是这两个页面有问题, 主页和我两个页面是正常的

另外两个页面的约束似乎不太一样😊

主页:
![image](https://user-images.githubusercontent.com/6214936/116420736-d64b6180-a870-11eb-91c5-f0d56f130942.png)

我:
![image](https://user-images.githubusercontent.com/6214936/116420774-dfd4c980-a870-11eb-90d4-d52afdadafbe.png)

**Comment by nagaame** [comment]
不过约束这个可能是小问题, 也可能是我误会了, 刚刚看了一下readme的示例图, 我把ipad横屏显示发现就可以了😂

**Comment by JoneWang** [comment]
好的，我会查看以上问题，可能在下月才有空做修改。
另外，在完成修复前，这个 issue 保持 open 状态。

**Comment by JoneWang** [comment]
因为 SwiftUI 的一些限制，目前还是保持不变：
1. Me 中 List 控件不够灵活，控制宽度会导致导航宽度也被固定。
2. 竖屏下默认隐藏侧边栏也是 NavigationView 和 NavigationLink 默认行为，目前没找到如何控制。

如果有什么好的方案可以提出。
