### ISSUE TITLE
战绩更新的问题

### ISSUE THREAD

**Issue by YodaYuuk1** [JoneWang/imink#11]
![75FD4112-A869-48E0-9725-CCF680F78AEE](https://user-images.githubusercontent.com/56193605/117554389-df66da80-b089-11eb-9218-7ce3fb88a432.png)
![0A770E91-5462-4CF0-B3BC-9ADEA1FB2916](https://user-images.githubusercontent.com/56193605/117554393-e1309e00-b089-11eb-8420-fc6af94dda1e.png)
![826D2C0A-B955-4C81-A257-45CE36242014](https://user-images.githubusercontent.com/56193605/117554394-e1c93480-b089-11eb-991a-35d48cff5b4a.png)

战绩更新有问题，最前面是我刚入坑的时候玩的，要翻一段时间才能看到最新的，但在翻一回又变成好久以前的战绩了，这是怎么回事？重新登陆好几次了。

**Comment by YodaYuuk1** [comment]
ios14.5 好久以前就有这个问题了

**Comment by YodaYuuk1** [comment]
ios14.5 好久以前就有这个问题了，也重下了两次

**Comment by JoneWang** [comment]
近期会发布一个小版本修复。
这个是排序有 bug。

**Comment by YodaYuuk1** [comment]
好滴好滴

**Comment by JoneWang** [comment]
[9001a0c](https://github.com/JoneWang/imink/commit/9001a0c3097c2eb4eae8bd61298d37405ccfe241)
将在 App Store 上的 1.0.6 版本中提供。
