### ISSUE TITLE
macos版输入token点ok后加载一下  然后回到输入页面

### ISSUE THREAD

**Issue by DaYu525** [JoneWang/imink#2]
macos版输入token点ok后加载一下  然后回到输入页面   token应该没问题的   为了确保    专门把tg上的机器人重新获取了一次token   get & set successful    然后再拿了一次clienttoken   内容跟第一次拿到的一样 ， 输入 加载 返回输入页

**Comment by JoneWang** [comment]
已修复，麻烦再次尝试一下。

另外，目前的 macOS 版本不再维护，新版在开发中，可先尝试使用 iOS testflight。

**Comment by DaYu525** [comment]
还是不行  跟之前一样   没事不用管了  我就是试用一下   用tg bot就可以了     testflight限制ios版本  就没搞了  x不想升ios14  怕卡    ，机器人做的非常好 尤其是新出的查看个人资料，能查到很多官方app上没有的数据，很赞，作为一个新手开发者，都想用java写一遍了，闲了试试。

**Comment by JoneWang** [comment]
试一下在 bot 中发送 /resetclienttoken 之后，使用新的 token 登录。
