### ISSUE TITLE
登录验证问题

### ISSUE THREAD

**Issue by Jelly27** [JoneWang/imink#35]
[![7hsyL9.png](https://s4.ax1x.com/2022/01/22/7hsyL9.png)](https://imgtu.com/i/7hsyL9)

登录验证时出现如图问题请问如何解决，设备是iPad mini 5，iOS 15.1

**Comment by JoneWang** [comment]
这个问题是由于在 /Account/Login 这个步骤中所请求的域名在中国大陆地区访问不畅所导致的。
域名见：
https://github.com/JoneWang/imink/blob/af3319ba2ce683c068f909af0f550229e50011ca/imink/Shared/API/NSOAPI.swift#L49

**Comment by Jelly27** [comment]
已经代理尝试直接访问会返回{"status": 9402, "errorMessage": "Resource not found.", "correlationId": "f4075c93-77db070e"}，还是同样的问题

**Comment by JoneWang** [comment]
> 已经科学上网，尝试直接访问会返回
> `{"status": 9402, "errorMessage": "Resource not found.", "correlationId": "f4075c93-77db070e"}`
> 登录还是同样的问题

返回此信息说明已经可以成功请求此域名，此返回结果是因为缺少必要参数。
请在 imink 中再次尝试登录。

**Comment by JoneWang** [comment]
> > 已经科学上网，尝试直接访问会返回
> > `{"status": 9402, "errorMessage": "Resource not found.", "correlationId": "f4075c93-77db070e"}`
> > 登录还是同样的问题
> 
> 返回此信息说明已经可以成功请求此域名，此返回结果是因为缺少必要参数。 请在 imink 中尝试登录，确保在安装 imink 的设备上能访问此域名。（如使用代理工具，尝试全局）

**Comment by Jelly27** [comment]
是使用同一设备访问出现的，全局代理也这样，路由和软件代理都试了，每次只开一个代理，结果都是这样，没办法的话就不麻烦了，感谢感谢

**Comment by JoneWang** [comment]
> 是使用同一设备访问出现的，全局代理也这样，路由和软件代理都试了，每次只开一个代理，结果都是这样，没办法的话就不麻烦了，感谢感谢

原来如此。想查明一下问题原因，是否可以尝试使用 http 抓包工具查看一下 /Account/Login 这一步骤的请求信息呢？

**Comment by Jelly27** [comment]
抓包结果是最后一步失败返回json如下
`{
  "status" : 9427,
  "errorMessage" : "Upgrade required.",
  "correlationId" : ""
}
`
应该是请求的客户端版本低
https://github.com/JoneWang/imink/blob/af3319ba2ce683c068f909af0f550229e50011ca/imink/Shared/Data/AppUserDefaults.swift#L51
iOS nso最新版本号是1.14.0，修改一下看看是否能解决

**Comment by JoneWang** [comment]
> 抓包结果是最后一步失败返回json如下
> 
> `{   "status" : 9427,   "errorMessage" : "Upgrade required.",   "correlationId" : "" }`
> 
> 应该是请求的客户端版本低，iOS nso最新版本号是1.14.0，修改一下看看是否能解决
> 
> https://github.com/JoneWang/imink/blob/af3319ba2ce683c068f909af0f550229e50011ca/imink/Shared/Data/AppUserDefaults.swift#L51

感谢～
imink 在启动时会请求会请求 https://api.imink.jone.wang/config 获取最新的版本号，不过看你的情况是这个版本未正确设置，我检查一下这问题。

**Comment by Jelly27** [comment]
> 

是在国区商店下载的，版本1.4.0(107)，抓包的结果里请求头字段
`
X-ProductVersion:1.12.0
User-Agent:com.nintendo.znca/1.12.0(iOS/14.2)
`

**Comment by JoneWang** [comment]
> 是在国区商店下载的，版本1.4.0(107)，抓包的结果里请求头字段
> `X-ProductVersion:1.12.0 User-Agent:com.nintendo.znca/1.12.0(iOS/14.2)`

看看在启动应用时，是否有请求 https://api.imink.jone.wang/config

**Comment by Jelly27** [comment]
> > 是在国区商店下载的，版本1.4.0(107)，抓包的结果里请求头字段
> > `X-ProductVersion:1.12.0 User-Agent:com.nintendo.znca/1.12.0(iOS/14.2)`
> 
> 看看在启动应用时，是否有请求 https://api.imink.jone.wang/config

不知为何今天可以正常登录了……，版本号和任天堂的服务器都是正常响应的
`
{
  "nso_version":"1.14.0"
}
`
可能是关闭进程再次启动的时候获取到的版本号吧……我正在尝试重装关代理看看能不能复现一下不能登录的问题

**Comment by Jelly27** [comment]
> > 是在国区商店下载的，版本1.4.0(107)，抓包的结果里请求头字段
> > `X-ProductVersion:1.12.0 User-Agent:com.nintendo.znca/1.12.0(iOS/14.2)`
> 
> 看看在启动应用时，是否有请求 https://api.imink.jone.wang/config

启动的时候请求版本号地址，如果没请求成功会使用默认的1.12.0，可能是因为我习惯直接返回桌面一直没有关应用，第一次打开请求失败了就一直用1.12.0登录的

**Comment by JoneWang** [comment]
> > > 是在国区商店下载的，版本1.4.0(107)，抓包的结果里请求头字段
> > > `X-ProductVersion:1.12.0 User-Agent:com.nintendo.znca/1.12.0(iOS/14.2)`
> > 
> > 
> > 看看在启动应用时，是否有请求 https://api.imink.jone.wang/config
> 
> 启动的时候请求版本号地址，如果没请求成功会使用默认的1.12.0，可能是因为我习惯直接返回桌面一直没有关应用，第一次打开请求失败了就一直用1.12.0登录的

看来在每次登录前获取一次 version 会比较保险
