### ISSUE TITLE
获取f的api还能正常使用吗

### ISSUE THREAD

**Issue by ShaddollAsu** [JoneWang/imink#39]
请问获取`f`能用于`/v3/Account/Login`吗
我试了一下，返回的`{"status": 9403, "errorMessage": "Invalid token."...`
但我请求`/v2/Account/Login`也是这个9403错误

**Comment by JoneWang** [comment]
可以正常使用，返回 `Invalid token` 应该是数据有误。
请参照 [imink API 文档](https://github.com/JoneWang/imink/wiki/imink-API-Documentation)或 [imink 代码](https://github.com/JoneWang/imink/blob/dfa4c891b69ae0752d0c57badd90eb705643b978/imink/Shared/API/NSOAuthorization.swift#L150)。

**Comment by ShaddollAsu** [comment]
更正了几个参数，我现在请求`/v2/Account/Login`返回`{"status": 9427, "errorMessage": "Upgrade required.",...`
`/v3/Account/Login`的请求用的是id_token而不是access_token，我怀疑这个`f`可能不能用于`/v3/Account/Login`

**Comment by ShaddollAsu** [comment]
> 可以正常使用，返回 `Invalid token` 应该是数据有误。 请参照 [imink API 文档](https://github.com/JoneWang/imink/wiki/imink-API-Documentation)或 [imink 代码](https://github.com/JoneWang/imink/blob/dfa4c891b69ae0752d0c57badd90eb705643b978/imink/Shared/API/NSOAuthorization.swift#L150)。

更正了几个参数，我现在请求`/v2/Account/Login`返回`{"status": 9427, "errorMessage": "Upgrade required.",...`
`/v3/Account/Login`的请求用的是id_token而不是access_token，我怀疑这个`f`可能不能用于`/v3/Account/Login`

**Comment by JoneWang** [comment]
> 更正了几个参数，我现在请求`/v2/Account/Login`返回`{"status": 9427, "errorMessage": "Upgrade required.",...` `/v3/Account/Login`的请求用的是id_token而不是access_token，我怀疑这个`f`可能不能用于`/v3/Account/Login`

遇到 `Upgrade required` 是由于需要将 `User-Agent` 版本号修改为当前 NSO 最新版本号，例如目前是 `2.0.0`。
`/v3/Account/Login` 可以使用，但后续的 `/Game/GetWebServiceToken` 需要使用 `v2`。

**Comment by JoneWang** [comment]
**OT** `api.imink.jone.wang` 接口地址在接下来会变更为 `api.imink.app`（旧地址依然会保留一段时间）。

**Comment by ShaddollAsu** [comment]
>

**Comment by ShaddollAsu** [comment]
我现在是用`https://accounts.nintendo.com/connect/1.0.0/api/token`里的`access_token`
再加上python的`request_id=str(uuid.uuid1())`和`timestamp=str(int(time.time()))`
去请求`https://api.imink.app/f`得到`f`
之后用
```
{
    "parameter": {
        "requestId": request_id,
        "naIdToken": access_token,
        "naBirthday": xxx,
        "naCountry": xxx,
        "timestamp": int(timestamp),
        "language": xxx,
        "f": f,
    }
}

accept： application/json
authorization： Bearer
accept-encoding： gzip, deflate, b
x-platform：Android
x-productversion：2.0.0
user-agent：com.nintendo.znca/2.0.0 (iOS/14.2)
```
请求`https://api-lp1.znc.srv.nintendo.net/v2/Account/Login`
就会得到`{"status": 9400, "errorMessage": "Bad request.",...}`

请求`https://api-lp1.znc.srv.nintendo.net/v3/Account/Login`也是类似，一个成功的请求，替换掉上述4个参数，
就会得到`{"status": 9403, "errorMessage": "Invalid token.",...}`

**Comment by JoneWang** [comment]
你出现的错误还是由于请求参数有误导致的。
我的另一个项目 [Sp2BattleBot](https://github.com/JoneWang/sp2battlebot) 是使用 Python 实现的，你也可以参考[请求 f 的部分代码](https://github.com/JoneWang/sp2battlebot/blob/671e4fa6ec8839271e2ff377c83be6c704d3e3a4/sp2bot/splatoon2.py#L427)。
此项目同样可正常使用。

**Comment by ShaddollAsu** [comment]
参考了，`https://api-lp1.znc.srv.nintendo.net/v2/Account/Login`的header必须要带`content-type`才能请求成功，
你这里应该是网络库会自动补上吧
但是`https://api-lp1.znc.srv.nintendo.net/v3/Account/Login`还是无法成功，
你是如何请求`v3`的

**Comment by JoneWang** [comment]
> 参考了，`https://api-lp1.znc.srv.nintendo.net/v2/Account/Login`的header必须要带`content-type`才能请求成功， 你这里应该是网络库会自动补上吧 但是`https://api-lp1.znc.srv.nintendo.net/v3/Account/Login`还是无法成功， 你是如何请求`v3`的

![image](https://user-images.githubusercontent.com/1433612/158552215-9b979062-7c93-4f62-a272-7832f31c7e53.png)

**Comment by ShaddollAsu** [comment]
改成`access_token`去请求，成功了
谢谢大佬

**Comment by ShaddollAsu** [comment]
还得麻烦问下，`https://api.imink.app/f`的请求频率大概是多少

**Comment by JoneWang** [comment]
> 还得麻烦问下，`https://api.imink.app/f`的请求频率大概是多少

目前来说无限制。
如果长期使用 imink api，麻烦让我知道使用的 User-Agent 是什么，避免大量请求后被 ban。

另外，如果能帮到你，请 App Store 上给 imink 一个五星或者捐助此项目~（如果不想，您依然可以正常使用 imink api ❤️ ）
