### ISSUE TITLE
Feature request to import data from ikaWidget2

### ISSUE THREAD

**Issue by fishswing** [JoneWang/imink#42]
As ikaWidget2 is often having issues syncing with NT server, it would be helpful if imink can import data from ika.
Currently I have ~5000 salmon run records in ika. It would be much grateful if this feature can help me totally migrate from ika to imink.

\\
ikaWidget2 is able to export 3 types of data: The private format (.ikax), JSON format (saved as .zip), and CSV format. I can provide all help if any sample data is needed.

**Comment by ezioruan** [comment]
Hi, it is already practicable to import JSON data exported from ikaWidget. You can follow the steps illustrated in the attachment which I hope you’d find helpful of it. FYI, it seems ikaWidget does not support exporting Salmon Run records using JSON currently, so there are indeed some limitations regarding your need.
![IMG_0310](https://user-images.githubusercontent.com/631411/170913004-668f38df-8602-409c-8848-6b3cc9136d54.PNG)

**Comment by fishswing** [comment]
Thank u! I've successfully merged all battle data.
Sad news that salmon run results are unable to export. I will wait for ika auther's future updates.
