### ISSUE TITLE
在 iOS16 启动卡空白页

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [JoneWang/imink#43]
如题，不过小组件还能正常刷新
图一是小组件，图二是启动后状态
![C2B01907-49D5-4AC1-83AE-0A5BB23ECE95](https://user-images.githubusercontent.com/30079825/173222270-eb76a669-aabe-4a27-acda-94fd113ae7dd.png)
![2E8397C1-8B67-4677-97C0-7F28971F7590](https://user-images.githubusercontent.com/30079825/173222275-302ab980-86f4-48f7-9125-5eaa2168725e.png)

**Comment by GeekyMax** [comment]
@JoneWang 有修复计划么？

**Comment by JoneWang** [comment]
> @JoneWang 有修复计划么？

在 iOS16 环境中调试需要 Xcode14、macOS Ventura，Ventura 却无法兼容 Xcode13。因为自己还必须使用 Xcode13，所以没有环境去调试这个问题。
如果上面的问题得到解决或 Xcode14 正式版发布，会修复此问题。

**Comment by JoneWang** [comment]
在 iOS16 正式版中测试没有发现此问题。
